// src/models/User.js
// This file serves as a conceptual representation of the User model.
// If you are using an ORM like Prisma or Sequelize, you'd define models there.
// For Supabase, you'd define the 'users' table in the Supabase dashboard.
// This JS representation helps in understanding the structure.

/*
Example User schema:

{
  id: 'user_uuid_string', // Primary key, can be generated by Supabase UUID or simple string
  created_at: 'timestamp',
  name: 'string', // Name of the contact person
  whatsappNumber: 'string', // WhatsApp number, used for login/identification. Must be unique.
  businessName: 'string',
  businessType: 'string', // e.g., 'Makanan', 'Kerajinan', 'Pakaian'
  // Add other fields like email, password_hash (if using traditional auth), etc.
}
*/

// For now, we'll export an empty object as it's conceptual.
// Actual database schema definition happens in Supabase or your chosen DB.
module.exports = {};
